# Generated by Django 5.2.4 on 2025-07-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacao',
            name='vegetariano',
            field=models.BooleanField(default=False),
        ),
    ]
