# Generated by Django 5.2.4 on 2025-07-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_alimentacao_vegetariano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestuario',
            name='tamanho',
            field=models.CharField(max_length=20),
        ),
    ]
